# Generated by Django 4.2.20 on 2025-04-20 15:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Fund ID')),
                ('name', models.CharField(max_length=200, verbose_name='Fund Name')),
                ('manager', models.CharField(max_length=20, verbose_name='Fund Manager')),
                ('description', models.CharField(max_length=20, verbose_name='Fund Description')),
                ('net_asset_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fund Net Asset Value (NAV)')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fund Date of Creation')),
                ('performance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Fund Performance (as a apercentage)')),
            ],
            options={
                'verbose_name_plural': ['funds'],
                'ordering': ['performance'],
            },
        ),
    ]
