# Generated by Django 4.2.20 on 2025-04-20 20:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'ordering': ['id'], 'verbose_name_plural': ['funds']},
        ),
        migrations.AlterField(
            model_name='fund',
            name='performance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Fund Performance (as a percentage)'),
        ),
    ]
