# Generated by Django 4.2.20 on 2025-04-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_alter_fund_options_alter_fund_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Fund Description'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='manager',
            field=models.CharField(max_length=100, verbose_name='Fund Manager'),
        ),
    ]
